Add lesson 15
groting/Ror_Railway pull request #1
Opened 2017-04-25 15:28 UTC by groting

2017-04-26 07:28 UTC, iBublik requested changes

2017-04-26 07:28 UTC, iBublik commented on app/controllers/wagons_controller.rb
> +    respond_to do |format|
А зачем тут respond_to? У тебя всего один формат же

2017-04-26 07:28 UTC, iBublik commented on db/migrate/20170425134217_create_wagons.rb
> +      t.integer :high
Не самые удачные названия атрибутов, из них непонятно что там хранится

2017-04-26 07:28 UTC, iBublik commented on db/migrate/20170425134451_add_wagons_to_train.rb
> +    add_belongs_to :wagons, :train
Добавь еще внешний ключ для контроля целостности

2017-04-26 07:28 UTC, iBublik commented on app/views/trains/show.html.erb
> +    <%= @train.wagons.where("wagon_type == 'Купейный'").count%>
Не очень хорошо держать такой код во вьюхах. Лучше в модели поездов сделать метод `def wagons_count(wagon_type); ... end`, который возвращает число вагонов такого типа в поезде

2017-04-26 07:28 UTC, iBublik commented on app/views/trains/show.html.erb
> +  <% low_count_k, low_count_p, high_count_k, high_count_p = 0, 0, 0, 0 %>
Этому тоже явно не место во вьюхе. Создай в модели метод, который принимает тип вагона и положение места (верхнее/нижнее), а отдает число

2017-04-27 10:54 UTC, groting commented on db/migrate/20170425134451_add_wagons_to_train.rb
> +    add_belongs_to :wagons, :train
Можете уточнить эту часть, пожалуйста.

2017-04-29 20:10 UTC, vkurennov approved these changes

2017-04-29 20:10 UTC, vkurennov commented on app/controllers/wagons_controller.rb
> +      if @wagon.save
Отступы поехали

2017-04-29 20:10 UTC, vkurennov commented on app/controllers/wagons_controller.rb
> +      if @wagon.update(wagon_params)
И тут отступы слишком большие

2017-04-29 20:10 UTC, vkurennov commented on app/controllers/wagons_controller.rb
> +      redirect_to wagons_url, notice: 'Вагон удален!'
Отступ съехал

2017-04-29 20:10 UTC, vkurennov commented on app/models/train.rb
> +    wagons.where("wagon_type == '#{wagon_type}'").count
в sql сравнение - это одиночное равно, а не двойное. но вообще, это записыавется через ARel (об этом в следующем уроке) так: `wagons.where(wagon_type: wagon_type).count`

2017-04-29 20:10 UTC, vkurennov commented on db/migrate/20170425134451_add_wagons_to_train.rb
> +    add_belongs_to :wagons, :train
Имеется в виду опция `foreign_key: true`

2017-04-30 05:43 UTC, webmstk commented on db/migrate/20170425134217_create_wagons.rb
> +      t.belongs_to :train_id
Надо запомнить, не пиши `_id`, когда добавляешь связь. Просто `belongs_to :train`

2017-04-30 05:45 UTC, webmstk commented on db/schema.rb
> +    t.integer  "train_id_id"
О чём я и говорил

2017-05-10 12:58 UTC, merged