Add lesson 18
groting/Ror_Railway pull request #4
Opened 2017-05-18 16:47 UTC by groting

2017-05-18 18:33 UTC, vkurennov requested changes

2017-05-18 18:33 UTC, vkurennov commented on app/controllers/admin/base_controller.rb
> +before_action :authenticate_user!
Отступы

2017-05-18 18:33 UTC, vkurennov commented on app/controllers/admin/base_controller.rb
> +
Зачем пустая строка?

2017-05-18 18:33 UTC, vkurennov commented on app/controllers/admin/tickets_controller.rb
> +  @ticket = Ticket.find(params[:id])
Отступы

2017-05-18 18:33 UTC, vkurennov commented on app/views/admin/tickets/_form.html.erb
> +  <div class="field">
Из задания:

> Также администратор может создавать билеты для любого зарегистрированного пользователя, выбирая их из списка.

Где выбор из списка? ФИО должно остаться, но билет должен быть привязан к какому-то пользователю в системе. Его и выбирает админ из списка.

2017-05-20 13:29 UTC, groting commented on app/views/admin/tickets/_form.html.erb
> +  <div class="field">
В первом div есть выбор пользователя из списка.

2017-05-20 13:30 UTC, groting commented on app/views/admin/tickets/_form.html.erb
> +  <div class="field">
Тут

2017-05-20 14:31 UTC, vkurennov approved these changes

2017-05-20 14:31 UTC, vkurennov commented on app/views/admin/tickets/_form.html.erb
> +    <%= f.collection_select :user_id, User.all, :id, :email %>
Ок, но у тебя в контроллере нет user_id в ticket_params

2017-05-20 15:11 UTC, merged